Repository Lesser-cuckoo/qintodo-next-cuckoo, pull requests merged in 2022-02, with the labels that each got.

#2 環境構築の実施
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  package.json
  pages/_app.tsx
  pages/index.tsx
  src/layout/AuthLayout.tsx
  src/layout/index.ts
  src/lib/SupabaseClient.ts
  yarn.lock
Labels: documentation, enhancement

#4 タスク追加・表示の実装
  README.md
  src/lib/Datetime.ts
  src/lib/SupabaseClient.ts
  src/pages/index/index.tsx
Labels: enhancement

#13 :bug: 連打で同一タスクが複数回登録されるバグを修正 (Fixes #11)
  src/pages/index/index.tsx
Labels: bug

#23 ✨ タスクの編集機能の実装
  src/component/Input/index.tsx
  src/lib/SupabaseClient.ts
  src/pages/index/index.tsx
Labels: enhancement

#33 タスクの並び順の導入と並び順変更用デモコードを追加
  README.md
  src/lib/SupabaseClient.ts
  src/pages/index/index.tsx
Labels: enhancement

#42 ✨ Taskの削除機能を実装
  src/lib/SupabaseClient.ts
  src/pages/index/index.tsx
Labels: enhancement

#44 タスクを追加するボタンのUI/UX向上、その他変更
  src/component/NewTask/index.tsx
  src/component/RadioButton/index.tsx
  src/component/RadioButton/radiobutton.tsx
  src/component/TaskWrap/index.tsx
  src/component/taskInput/index.tsx
  src/lib/SupabaseClient.ts
  src/pages/index/index.tsx
Labels: enhancement

#47 ✨ 編集時のTodoの文字数制限を実装する
  src/component/RadioButton/index.tsx
  src/component/RadioButton/radiobutton.tsx
  src/component/TaskWrap/index.tsx
  src/component/taskInput/index.tsx
  src/constants/TaskElement.ts
  src/type/type.ts
Labels: enhancement

#56 ✨ アカウント画面の作成
  pages/mypage.tsx
  pages/mypage/index.tsx
  pages/mypage/profile/index.tsx
  src/layout/MypageLayout.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/profile/index.spec.tsx
  src/pages/mypage/profile/index.tsx
Labels: enhancement
